# Generated by Django 5.2.7 on 2025-10-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('categorie_brand', models.CharField(choices=[('luxury', 'Luxury'), ('mid-range', 'Mid-Range'), ('budget', 'Budget')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('stil_ceas', models.CharField(choices=[('clasic', 'Clasic'), ('modern', 'Modern'), ('sport', 'Sport'), ('luxury', 'Luxury')], max_length=20)),
                ('gen', models.CharField(choices=[('barbati', 'Barbati'), ('femei', 'Femei')], max_length=10)),
                ('rezistent_apa', models.CharField(choices=[('da', 'Da'), ('nu', 'Nu')], max_length=3)),
                ('tip_ceas', models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('smartwatch', 'Smartwatch')], max_length=15)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id_depozit', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('locatie', models.CharField(max_length=255)),
                ('numar_angajati', models.IntegerField()),
                ('disponibilitate_stoc', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tip_material', models.CharField(choices=[('piele', 'Piele'), ('otel inoxidabil', 'Otel inoxidabil'), ('plastic', 'Plastic'), ('ceramica', 'Ceramica')], max_length=20)),
                ('descriere', models.TextField()),
                ('durabilitate', models.CharField(choices=[('scazuta', 'Scazuta'), ('medie', 'Medie'), ('ridicata', 'Ridicata')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id_promotie', models.AutoField(primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=100)),
                ('tip_promotie', models.CharField(choices=[('reducere', 'Reducere procentuala'), ('oferta', 'Oferta speciala'), ('cadou', 'Produs cadou')], max_length=20)),
                ('procent_reducere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ceas',
            fields=[
                ('id_ceas', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.IntegerField(null=True)),
                ('data_lansare', models.DateField()),
                ('disponibil_online', models.BooleanField(default=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('colorCode', models.CharField(max_length=7)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_brand', to='aplicatie.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_categorie', to='aplicatie.categorie')),
                ('depozit', models.ManyToManyField(related_name='ceas_depozit', to='aplicatie.depozit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_material', to='aplicatie.material')),
                ('promoti', models.ManyToManyField(related_name='ceas_promitie', to='aplicatie.promotie')),
            ],
        ),
    ]
