# Generated by Django 5.2.7 on 2025-11-18 22:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('categorie_brand', models.CharField(choices=[('luxury', 'Luxury'), ('mid-range', 'Mid-Range'), ('budget', 'Budget')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('stil_ceas', models.CharField(choices=[('clasic', 'Clasic'), ('modern', 'Modern'), ('sport', 'Sport'), ('luxury', 'Luxury')], max_length=20)),
                ('gen', models.CharField(choices=[('barbati', 'Barbati'), ('femei', 'Femei')], max_length=10)),
                ('rezistent_apa', models.CharField(choices=[('da', 'Da'), ('nu', 'Nu')], max_length=3)),
                ('tip_ceas', models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('smartwatch', 'Smartwatch')], max_length=15)),
                ('descriere', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id_depozit', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('locatie', models.CharField(max_length=255)),
                ('numar_angajati', models.IntegerField()),
                ('disponibilitate_stoc', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tip_material', models.CharField(choices=[('piele', 'Piele'), ('otel inoxidabil', 'Otel inoxidabil'), ('plastic', 'Plastic'), ('ceramica', 'Ceramica')], max_length=20)),
                ('descriere', models.TextField()),
                ('durabilitate', models.CharField(choices=[('scazuta', 'Scazuta'), ('medie', 'Medie'), ('ridicata', 'Ridicata')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id_promotie', models.AutoField(primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=100)),
                ('tip_promotie', models.CharField(choices=[('reducere', 'Reducere procentuala'), ('oferta', 'Oferta speciala'), ('cadou', 'Produs cadou')], max_length=20)),
                ('procent_reducere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tara', models.CharField(blank=True, max_length=100, null=True)),
                ('oras', models.CharField(blank=True, max_length=100, null=True)),
                ('adresa', models.CharField(blank=True, max_length=255, null=True)),
                ('puncte_loialitate', models.IntegerField(default=0)),
                ('cont_premium', models.BooleanField(default=False)),
                ('cod', models.CharField(blank=True, max_length=100, null=True)),
                ('email_confirmat', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ceas',
            fields=[
                ('id_ceas', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.IntegerField(null=True)),
                ('data_lansare', models.DateField()),
                ('disponibil_online', models.BooleanField(default=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('colorCode', models.CharField(max_length=7)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_brand', to='aplicatie.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_categorie', to='aplicatie.categorie')),
                ('depozit', models.ManyToManyField(related_name='ceas_depozit', to='aplicatie.depozit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceas_material', to='aplicatie.material')),
                ('promotii', models.ManyToManyField(blank=True, related_name='ceas_promitie', to='aplicatie.promotie')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_tranzit', 'In tranzit'), ('livrat', 'Livrat'), ('anulat', 'Anulat'), ('procesare', 'In procesare')], default='procesare', max_length=20)),
                ('curier', models.CharField(max_length=100)),
                ('comanda_rapida', models.BooleanField(default=False)),
                ('ceasuri', models.ManyToManyField(related_name='comenzi', to='aplicatie.ceas')),
                ('useri', models.ManyToManyField(related_name='comenzi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateField()),
                ('subiect_email', models.CharField(default='Nu rata oferta!', max_length=100)),
                ('fisier_template', models.CharField(choices=[('oferta_standard.txt', 'Standard'), ('oferta_urgenta.txt', 'Urgent')], default='oferta_standard.txt', max_length=50)),
                ('procent_reducere', models.IntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(related_name='oferte', to='aplicatie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('comentariu', models.TextField()),
                ('data_adaugare', models.DateField(auto_now_add=True)),
                ('achizitie_verificata', models.BooleanField(default=False)),
                ('ceas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuri', to='aplicatie.ceas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ceas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.ceas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id_voucher', models.AutoField(primary_key=True, serialize=False)),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('procent_discont', models.IntegerField()),
                ('data_expirarii', models.DateField()),
                ('activ', models.BooleanField(default=True)),
                ('useri', models.ManyToManyField(related_name='vouchere', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
