# Generated by Django 5.2.7 on 2025-10-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceas',
            name='promoti',
        ),
        migrations.AddField(
            model_name='ceas',
            name='promotii',
            field=models.ManyToManyField(blank=True, related_name='ceas_promitie', to='aplicatie.promotie'),
        ),
    ]
