# Generated by Django 5.2.7 on 2025-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
