# Generated by Django 5.2.7 on 2025-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_remove_ceas_promoti_ceas_promotii'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
