# Generated by Django 5.2.7 on 2025-12-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_customuser_telefon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza ofertele speciale')]},
        ),
    ]
