# Generated by Django 5.2.7 on 2025-12-25 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0004_customuser_blocat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='ceasuri',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='useri',
        ),
        migrations.AddField(
            model_name='comanda',
            name='data_plasare',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comenzi_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProdusComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('ceas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.ceas')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse_comanda', to='aplicatie.comanda')),
            ],
        ),
    ]
